server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/monolith_bank
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  key: 20005947-30cc-41e7-a4cd-11face749120
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

logging:
  level:
    com.example.sabina.api: DEBUG
