global:
  scrape_interval:     10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "spring_micrometer"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8080"]

remote_write:
  - url: "<Your Prometheus remote_write endpoint>"
    basic_auth:
      username: "<Your Grafana Username>"
      password: "<Your Grafana API key>"
